services:
  - type: web
    name: sss-basketball
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
